### 1. Registrar um novo usuário (com SUCESSO)
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
    "name": "Natan Tavares",
    "email": "natan@email.com",
    "password": "password123"
}

### 2. Registrar um usuário (FALHA - E-mail duplicado)
# (Rode este APÓS o primeiro ter dado certo)
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
    "name": "Outro Natan",
    "email": "natan@email.com",
    "password": "outrasenha456"
}

### 3. Registrar um usuário (FALHA - Validação)
# (Senha muito curta)
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
    "name": "Usuario Teste",
    "email": "teste@email.com",
    "password": "123"
}

### 4. Fazer Login
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
    "email": "natan@email.com",
    "password": "password123"
}

### 5. Fazer Login (FALHA - senha incorreta)
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
    "email": "natan@email.com",
    "password": "password123456"
}

### 6. Fazer Login (FALHA - email inexistente)
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
    "email": "natasdsdan@email.com",
    "password": "password123456"
}